---
  # vim: set ft=ansible et ts=2 sw=2:
  #
  # Create a new VM from a template using the new vmware_guest module
  - name: VM from template
    hosts: local
    gather_facts: false
    connection: local
    vars:
      vc_hname: mgmt-vc02.labs.p1technologies.com
      vc_uname: "LABS\\johna"
      vc_passwd: "Verb947#City"
      dumpfacts: False
    tasks:
      - name: Shutdown VM
        vsphere_guest:
          validate_certs: no
          vcenter_hostname: '{{ vc_hname }}'
          username: '{{ vc_uname }}'
          password: '{{ vc_passwd }}'
          guest: '{{ name }}'
          state: powered_off
        delegate_to: localhost
      - name: Remove a VM
        vsphere_guest:
          validate_certs: no
          vcenter_hostname: '{{ vc_hname }}'
          username: '{{ vc_uname }}'
          password: '{{ vc_passwd }}'
          guest: '{{ name }}'
          state: absent
        delegate_to: localhost
