---
  # vim: set ft=ansible et ts=2 sw=2:
  #
  # Create a new VM from a template using the new vmware_guest module
  - name: VM from template
    hosts: local
    gather_facts: false
    connection: local
    vars:
      vc_hname: mgmt-vc02.labs.p1technologies.com
      vcenter_dc: "p1-labs"
      disk_size: 50
      disk_type: thin
      disk_ds: shared
      net_type: "static"
      net_dev: "vmxnet3"
      net_name: "Lab-VLAN50_ansible"
      net_vlan: "50"
      net_mask: "255.255.255.0"
      net_gw: "192.168.50.254"
      vmcluster: "Lab Cluster"
      vmfolder: "p1-labs/vm/Vast_Comm/CF_POC"
      dumpfacts: False
    tasks:
      - name: Check for required variables
        fail: msg="Must pass name, net_ip and vmtemplate to -e"
        when: name is not defined or net_ip is not defined or vmtemplate is not defined

      - name: Check for vSphere access parameters
        fail: msg="Must set vc_uname and vc_passwd in a Vault"
        when: (vc_uname is not defined) or (vc_passwd is not defined)
        
      - name: Create VM from template
        vmware_guest:
          validate_certs: False
          hostname: "{{ vc_hname }}"
          username: "{{ vc_uname }}"
          password: "{{ vc_passwd }}"
          esxi_hostname: "{{ esxhost | default('p1-lab-esx01.labs.p1technologies.com') }}"
          datacenter: "{{ vcenter_dc }}"
          name: "{{ name }}"
          template: "{{ vmtemplate }}"
          folder: "{{ vmfolder }}"
          disk:
            - size_gb: "{{ disk_size }}"
              type: "{{ disk_type }}"
              datastore: "{{ disk_ds }}"
          networks:
            - type: "{{ net_type }}"
              device_type: "{{ net_dev }}"
              name: "{{ net_name }}"
              vlan: "{{ net_vlan }}"
              ip: "{{ net_ip }}"
              netmask: "{{ net_mask }}"
              gateway: "{{ net_gw }}"
          hardware:
            num_cpus: "{{ vm_cpus | default(1) }}"
            memory_mb: "{{ vm_memory | default(2048) }}"
          state: present
        register: newvm
        
      - name: IP address info
        debug:
          msg: "{{ newvm.instance.ipv4 }} {{ name }}"
      - name: startup after
        vmware_guest:
          validate_certs: no
          hostname: "{{ vc_hname }}"
          username: "{{ vc_uname }}"
          password: "{{ vc_passwd }}"
          name: "{{ name }}"
          folder: "{{ vmfolder }}"
          state: poweredon
        delegate_to: localhost
      - name: Wait for ssh
        wait_for:
          host: "{{ name }}"
          port: 22
          delay: 30
      - name: httpd conf file
        delegate_to: "{{ name }}"
        lineinfile:
          path: /etc/httpd/conf/httpd.conf
          regexp: '^Listen '
          line: "Listen {{ net_ip }}:80"
      - name: httpd reload
        delegate_to: "{{ name }}"
        service:
          name: httpd
          state: reloaded

