---
  # vim: set ft=ansible et ts=2 sw=2:
  #
  # Create a new VM from a template using the new vmware_guest module
  - name: VM from template
    hosts: local
    gather_facts: false
    connection: local
    vars:
      vc_hname: mgmt-vc02.labs.p1technologies.com
      vc_uname: "LABS\\johna"
      vc_passwd: "Verb947#City"
      vmfolder: "p1-labs/vm/Vast_Comm/CF_POC"
      dumpfacts: False
    tasks:
      - name: Shutdown VM
        vmware_guest:
          validate_certs: no
          hostname: '{{ vc_hname }}'
          username: '{{ vc_uname }}'
          password: '{{ vc_passwd }}'
          name: '{{ name }}'
          folder: '{{ vmfolder }}'
          state: poweredoff
        delegate_to: localhost
      - name: Remove a VM
        vmware_guest:
          validate_certs: no
          hostname: '{{ vc_hname }}'
          username: '{{ vc_uname }}'
          password: '{{ vc_passwd }}'
          name: '{{ name }}'
          folder: '{{ vmfolder }}'
          state: absent
        delegate_to: localhost
